# Generated by Django 5.1.3 on 2025-01-03 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phoneNumber', models.CharField(default='0000', max_length=10)),
                ('message', models.TextField()),
            ],
            options={
                'ordering': ['Fullname'],
            },
        ),
    ]
