# Generated by Django 5.1.3 on 2025-02-01 04:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('variant', '0001_initial'),
        ('wishlist', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wishlist',
            options={'ordering': ['variant_id']},
        ),
        migrations.RenameField(
            model_name='wishlist',
            old_name='variant',
            new_name='variant_id',
        ),
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('user', 'variant_id')},
        ),
    ]
