# Generated by Django 5.1.3 on 2024-12-10 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AddToCart', '0002_alter_cart_user_alter_cart_variant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['variant']},
        ),
    ]
