# Generated by Django 5.1.3 on 2024-11-25 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_remove_subscription_plan_remove_subscription_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refer_subscription',
            name='state',
        ),
    ]
