# Generated by Django 5.1.3 on 2024-11-25 10:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_alter_refer_subscription_referred_to_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='refer_subscription',
            new_name='referSubscription',
        ),
    ]
