# Generated by Django 5.1.3 on 2024-12-12 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_payment_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='UTR',
            field=models.CharField(default='blank', max_length=100),
        ),
    ]
