# Generated by Django 5.1.3 on 2024-12-10 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['variant']},
        ),
    ]
