# Generated by Django 5.1.3 on 2025-01-03 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchase', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productCode', models.CharField(default='default', max_length=100)),
                ('image', models.ImageField(upload_to='returns/')),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('return_date', models.DateTimeField(auto_now_add=True)),
                ('is_eligible', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=0)),
                ('request_type', models.CharField(choices=[('return', 'Return'), ('refund', 'Refund'), ('replacement', 'Replacement')], default='refund', max_length=20)),
                ('purchase_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='purchase.purchase')),
                ('user', models.ForeignKey(default='00', on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
