# Generated by Django 5.1.3 on 2024-12-16 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('return_page', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returnpage',
            name='refund_amount',
        ),
        migrations.AddField(
            model_name='returnpage',
            name='refund_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
