# Generated by Django 5.1.3 on 2024-12-16 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('return_page', '0002_remove_returnpage_refund_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='returnpage',
            old_name='refund_quantity',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='returnpage',
            name='return_type',
        ),
        migrations.AddField(
            model_name='returnpage',
            name='request_type',
            field=models.CharField(choices=[('return', 'Return'), ('refund', 'Refund'), ('replacement', 'Replacement')], default='refund', max_length=20),
        ),
    ]
