# Generated by Django 5.1.3 on 2024-12-16 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('return_page', '0003_rename_refund_quantity_returnpage_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnpage',
            name='productCode',
            field=models.CharField(default='default', max_length=100),
        ),
    ]
