# Generated by Django 5.1.3 on 2024-12-03 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(default='abc', max_length=250),
        ),
    ]
