# Generated by Django 5.1.3 on 2024-11-22 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='subscribe',
            field=models.BooleanField(default=False),
        ),
    ]
