# Generated by Django 5.1.3 on 2024-12-20 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['companyName'], 'verbose_name_plural': 'companies'},
        ),
    ]
