# Generated by Django 5.1.3 on 2025-01-03 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='material_type',
            field=models.CharField(default='abc', max_length=100),
        ),
        migrations.AddField(
            model_name='variant',
            name='orientation',
            field=models.CharField(choices=[('horizontal', 'Horizontal'), ('vertical', 'Vertical')], default='horizontal', max_length=200),
        ),
        migrations.AddField(
            model_name='variant',
            name='shape',
            field=models.CharField(default='rectangle', max_length=100),
        ),
    ]
