# Generated by Django 5.1.3 on 2024-12-10 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variant', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variant',
            options={'ordering': ['product', 'color']},
        ),
        migrations.RemoveField(
            model_name='variant',
            name='orientation',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='size',
        ),
        migrations.AddField(
            model_name='variant',
            name='material_type',
            field=models.CharField(default='abc', max_length=100),
        ),
        migrations.AddField(
            model_name='variant',
            name='shape',
            field=models.CharField(default='rectangle', max_length=100),
        ),
    ]
