# Generated by Django 5.1.3 on 2024-12-03 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='back_image',
            field=models.ImageField(null=True, upload_to='uploads/back_images/'),
        ),
        migrations.AddField(
            model_name='variant',
            name='front_image',
            field=models.ImageField(null=True, upload_to='uploads/front_images/'),
        ),
        migrations.AddField(
            model_name='variant',
            name='orientation',
            field=models.CharField(choices=[('horizontal', 'Horizontal'), ('vertical', 'Vertical')], default='horizontal', max_length=200),
        ),
    ]
