# Generated by Django 5.1.3 on 2024-12-10 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variant', '0002_alter_variant_options_remove_variant_orientation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='orientation',
            field=models.CharField(choices=[('horizontal', 'Horizontal'), ('vertical', 'Vertical')], default='horizontal', max_length=200),
        ),
    ]
