# Generated by Django 5.1.3 on 2025-01-03 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phoneNumber', models.CharField(default='0000', max_length=10)),
                ('query', models.TextField()),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('resolve', 'Resolve'), ('assigned', 'Assigned')], default='pending', max_length=20)),
                ('remarks', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['status'],
            },
        ),
    ]
