# Generated by Django 5.1.3 on 2024-12-13 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contact_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('resolve', 'Resolve'), ('assigned', 'Assigned')], default='pending', max_length=20)),
                ('remarks', models.CharField(max_length=100)),
                ('Email', models.ForeignKey(default='email', on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='contact_page.contact')),
                ('fullName', models.ForeignKey(default='default', on_delete=django.db.models.deletion.CASCADE, related_name='name', to='contact_page.contact')),
                ('message', models.ForeignKey(default='message', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='contact_page.contact')),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='contact_page.contact')),
            ],
            options={
                'ordering': ['status'],
            },
        ),
    ]
