# Generated by Django 5.1.3 on 2024-12-12 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contact_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('resolve', 'Resolve')], default='pending', max_length=20)),
                ('remarks', models.CharField(max_length=100)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='contact_page.contact')),
            ],
            options={
                'ordering': ['status'],
            },
        ),
    ]
