# Generated by Django 5.1.3 on 2024-12-13 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('query_ticket', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='fullName',
            new_name='Fullname',
        ),
    ]
