# Generated by Django 5.1.3 on 2024-12-13 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('query_ticket', '0002_rename_fullname_ticket_fullname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='Email',
            new_name='email',
        ),
    ]
