# Generated by Django 5.1.3 on 2024-12-13 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query_ticket', '0003_rename_email_ticket_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='Fullname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='query',
            field=models.TextField(),
        ),
    ]
