# Generated by Django 5.1.3 on 2025-01-03 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='banners/images/')),
            ],
            options={
                'verbose_name_plural': 'banners',
                'ordering': ['type'],
            },
        ),
    ]
