# Generated by Django 5.1.3 on 2025-02-01 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banners',
            name='type',
            field=models.CharField(choices=[('home', 'Home Page'), ('shop', 'Shop')], max_length=200),
        ),
    ]
