# Generated by Django 5.1.3 on 2024-12-10 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_description_products_orientation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='industry_type',
        ),
        migrations.RemoveField(
            model_name='products',
            name='orientation',
        ),
    ]
