# Generated by Django 5.1.3 on 2024-12-02 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_products_industry_type_alter_products_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='type',
            field=models.CharField(default='abc', max_length=100),
        ),
    ]
