# Generated by Django 5.1.3 on 2024-12-03 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_products_type'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='type',
            new_name='material_type',
        ),
        migrations.RemoveField(
            model_name='products',
            name='price',
        ),
        migrations.RemoveField(
            model_name='products',
            name='sellingPrice',
        ),
        migrations.AlterField(
            model_name='products',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.services'),
        ),
    ]
